### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by f-f** [csicar/purescript-sized-matrices#12]
We [had to drop this library from `package-sets`](https://github.com/purescript/package-sets/pull/565) due to it using an old version of `sized-vectors`.

I see that it has been updated to the latest, so I think cutting a new release should be enough to add it again to the set. I'll hold off for some days before tagging a new package set release, so there's some time to add it back there without breaking changes for downstream users

**Comment by csicar** [comment]
Good point. I've created a new release and pushed it to GH and bower.
The version is [`v1.0.0`](https://github.com/csicar/purescript-sized-matrices/releases/tag/v1.0.0)

**Comment by f-f** [comment]
@csicar thank you!
