### ISSUE TITLE
Make test suite pass / Add CI

### ISSUE THREAD

**Issue by m-bock** [csicar/purescript-sized-matrices#4]
I'd suggest that the test suite should always pass on master. Currently one test intentionally fails:

https://github.com/csicar/purescript-sized-matrices/blob/master/src/Data/Matrix/Algorithms.purs#L94

If it does not work yet it may be better suited in a separate branch.

To make sure this always is the case, there we could use some CI (e.g. travis) and protect the master branch with it.

**Comment by csicar** [comment]
100% on board.
I'll create a CI and move the LR-Decomposition and Gaussian algorithm to a separate branch.

**Comment by csicar** [comment]
Moved to separate branch: https://github.com/csicar/purescript-sized-matrices/tree/systems-linear-equations

**Comment by csicar** [comment]
CI integrated in 6cd5dcf1c35c323ee0e3a1fa87e9d38bdad8ef48
